// content.js
// Generated from IJSAP_WebTool_Content_v1.md (CONTENT_VERSION 1.1).
// The markdown content document is the canonical source. Do not edit this file by hand
// except the DEPLOYMENT CONSTANTS block below. To change any text: edit the markdown
// document, mirror the change here, and bump CONTENT_VERSION in both places.
// ID convention: dots in the content document's block IDs map to object nesting below
// (rubric.layer1.q1a.question -> IJSAP_CONTENT.rubric.layer1.q1a.question).

window.IJSAP_CONTENT = {

  CONTENT_VERSION: "1.1",
  RUBRIC_VERSION: "Final draft incorporating Editorial Board feedback, April 2026",

  meta: {

    // ===== DEPLOYMENT CONSTANTS: set these once after deployment =====
    links: {
      proposalTemplateURL: "SET_AT_DEPLOYMENT"
    },
    // ================================================================

    outcomes: [
      { string: "Not Suitable for IJSaP", setAt: ["Layer 1", "Layer 2"], color: "#6C3483" },
      { string: "Genre Redirect",         setAt: ["Layer 1"],            color: "#2471A3" },
      { string: "Administrative Return",  setAt: ["Layer 2"],            color: "#C0392B" },
      { string: "Developmental Return",   setAt: ["Layer 3"],            color: "#B7770D" },
      { string: "Revise Before Review",   setAt: ["Layer 3"],            color: "#B7770D" },
      { string: "Proceed to Review",      setAt: ["Layer 3"],            color: "#1E8449" }
    ],

    layers: ["Layer 1", "Layer 2", "Layer 3"],

    genres: {
      "Research Article": {
        key: "researchArticle",
        wordLimitText: "4,000 to 6,000",
        anonymization: "required",
        anonymizationLabel: "Required",
        reviewRoute: "Anonymized peer review"
      },
      "Case Study": {
        key: "caseStudy",
        wordLimitText: "3,000",
        anonymization: "required",
        anonymizationLabel: "Required",
        reviewRoute: "Anonymized peer review"
      },
      "Opinion Piece": {
        key: "opinionPiece",
        wordLimitText: "900",
        anonymization: "notRequired",
        anonymizationLabel: "Not required (normally reviewed within the EB)",
        reviewRoute: "EB review"
      },
      "Reflective Essay": {
        key: "reflectiveEssay",
        wordLimitText: "3,000",
        anonymization: "exempt",
        anonymizationLabel: "Exempt (dialogic review is not anonymized)",
        reviewRoute: "Dialogic review"
      },
      "Review": {
        key: "review",
        wordLimitText: "800",
        anonymization: "notRequired",
        anonymizationLabel: "Not required (normally reviewed within the EB)",
        reviewRoute: "EB review"
      }
    },

    // Deadlines are calculated from the date the email is generated, not the
    // assessment date, and formatted "Month D, YYYY".
    deadlines: {
      "Administrative Return": { optionsDays: [14, 21], defaultDays: 21 },
      "Developmental Return":  { optionsDays: [28, 42, 56], defaultDays: 56 },
      "Revise Before Review":  { optionsDays: [28, 42, 56], defaultDays: 28 }
    }
  },

  rubric: {

    // rubric.general [VERBATIM] — Stage 0, beneath the start form
    general: "Work through the three layers in order. As you read, note issues at all layers and address everything in a single communication to the author rather than stopping and communicating after each layer.\n\nOne co-editor completes the assessment. The other reviews and may edit it before it is sent. Where co-editors within a team disagree on a decision, or you are uncertain, the matter should be referred to Mick.",

    layer1: {

      // rubric.layer1.intro [VERBATIM] — Stage 1, above the two questions
      intro: "This is the first and most important gate. Layer 1 normally requires reading only the abstract, introduction, and conclusion, not the full paper, though skim reading the full paper may be needed to clarify whether the paper best fits a case study or reflective essay genre. There are two questions. A submission that does not meet the criterion in Question 1A is not suitable for IJSAP and should not proceed further. A submission that does not meet the criterion in Question 1B may be redirected to a more appropriate genre. These are different problems with different responses: Not Suitable for IJSAP means the work is not about partnership practice or process and belongs in another journal. A genre mismatch means the work may be appropriate for IJSAP but has been submitted under the wrong category.",

      q1a: {
        // [VERBATIM]
        question: "Is this submission genuinely about students-as-partners practice or process?",
        criteria: "Partnership must be the subject and focus of analysis, not merely the context or method through which something else was done. A project that involved students is not, by itself, a piece about the process of partnership.",
        ifNo: "Issue a Not Suitable for IJSAP outcome. Explain specifically how the submission is not about the practice of partnership or the process of working in partnership. Direct the author to a more appropriate venue. If the author would like to rework their submission or develop a submission about partnership practice or process, invite them to send a proposal using the journal's template."
      },

      q1b: {
        // [VERBATIM]
        question: "Does the content match the genre the author has claimed?",
        criteria: "Check whether the submission fits the claimed genre in terms of scope, structure, and purpose. Mismatches can sometimes be resolved by suggesting a different genre rather than returning outright.",
        ifNo: "Suggest the appropriate genre and invite the author to revise the submission accordingly. If no genre fits, explain why the submission falls outside the journal's current scope. This would normally involve a new submission as different criteria need to be met, and if a change from or to a reflective essay is involved then the paper will need to be anonymized or deanonymized."
      }
    },

    layer2: {

      // rubric.layer2.intro [VERBATIM] — Stage 2, above the checks
      intro: "These checks do not require reading the paper. They can be completed within a few minutes using the submission metadata and the file itself. If the submission is not in alignment, proceed with an Administrative Return. Formatting errors alone do not trigger an Administrative Return: if formatting is the only issue, note it and raise it at the feedback stage after review. If it appears alongside other lack of alignment, include it in the return communication. Sometimes it may be easier to change it yourself (e.g. anonymising the submission) rather than return it to the author.",

      checks: {
        wordCount: {
          // [VERBATIM]
          label: "Word count",
          text: "Word count is within the stated limit for the claimed genre (see Genre Reference table), or up to 5% over. Count excludes abstract, biographies, and reference list.",
          failAction: "adminReturn"
        },
        fileFormat: {
          // [VERBATIM]
          label: "File format",
          text: "Submitted as a Word document (.doc or .docx)",
          failAction: "adminReturn"
        },
        anonymization: {
          // [VERBATIM]
          label: "Anonymization",
          text: "Submission is anonymized correctly (required for Research Articles and Case Studies. Reflective Essays are exempt)",
          failAction: "adminReturn"
        },
        priorPublication: {
          // [VERBATIM]
          label: "Prior publication",
          text: "Submission is not previously published and is not under concurrent review elsewhere. A manuscript previously presented as a conference paper or a working paper is acceptable. The author checklist is the primary mechanism for confirming this.",
          failAction: "priorPublication"
        },
        ethicsStatement: {
          // [VERBATIM]
          label: "Ethics statement",
          text: "Ethics statement included if reporting on research involving human participants",
          failAction: "adminReturn"
        },
        formatting: {
          // [ADAPTED] — "Note:" prefix dropped, cross-reference reworded to the on-screen introduction
          label: "Basic formatting",
          text: "Basic formatting: 12pt Calibri, single spacing, 1-inch margins. Problems with formatting alone do not trigger an Administrative Return. See the introductory note above.",
          failAction: "noteOnly"
        }
      }
    },

    layer3: {

      // rubric.layer3.intro [VERBATIM] — Stage 3, above the genre block
      intro: "Layer 3 requires a full read. As you read, note points you would want the author to respond to, so you do not need to reread the article after reviews come in. The threshold question differs by genre. The outcome branches depend on what you find. Where the submission shows promise but needs targeted development before external reviewers see it, a Revise Before Review request is appropriate. Where the submission does not meet the threshold and requires more substantial work, issue a Developmental Return. Both outcomes use the same return process. The distinction is one of degree and is recorded in the assessment record. As a working guide: Revise Before Review applies when the required changes are specific and bounded and the submission is close to ready. Developmental Return applies when the work requires more substantial rethinking before it is ready for external scrutiny.",

      genres: {

        researchArticle: {
          // [VERBATIM]
          threshold: "Does this submission present a clear methodology and make a demonstrable contribution to knowledge in the field?",
          note: "A submission with no engagement with relevant academic literature, or only a very limited analysis of the data collected, should be treated as not ready for review, regardless of its other qualities.",
          findings: [
            {
              finding: "Methodology clear and contribution evident",
              outcome: "Proceed to Review",
              notes: "Note any points for reviewer guidance and/or later feedback to author before sending out."
            },
            {
              finding: "Methodology and/or contribution unclear, understated, absent, or implicit",
              outcome: "Revise Before Review or Developmental Return",
              notes: "Ask the author to clarify the methodology and contribution and their significance. Record which outcome applies and the key reason in the assessment record."
            }
          ]
        },

        caseStudy: {
          // [VERBATIM]
          threshold: "Does this submission go beyond description to offer genuine analysis, including identification of strengths, weaknesses, impacts, and transferability?",
          note: "The submission guidelines state explicitly that purely descriptive case studies will not be accepted. This is a clear line.",
          findings: [
            {
              finding: "Analytical, with strengths, weaknesses, impacts, and transferability addressed and relevant literature cited",
              outcome: "Proceed to Review",
              notes: "Note any points for reviewer guidance and/or later feedback to author before sending out."
            },
            {
              finding: "Overly descriptive: analysis insufficient, or strengths/weaknesses/impacts/transferability not adequately addressed",
              outcome: "Revise Before Review or Developmental Return",
              notes: "Identify the specific analytical gaps. Explain clearly what analytical work is expected. Record which outcome applies in the assessment record."
            }
          ]
        },

        opinionPiece: {
          // [VERBATIM]
          threshold: "Does this submission stake a clear position and support it with argument, evidence, or lived experience?",
          note: null,
          findings: [
            {
              finding: "Clear position, supported by argument or evidence, thought-provoking",
              outcome: "Proceed to Review",
              notes: "Note any points for reviewer guidance and/or later feedback to author before sending out. Note opinion pieces are normally reviewed within the EB."
            },
            {
              finding: "Position absent, underdeveloped, or unsupported. Reads as general reflection or summary",
              outcome: "Revise Before Review or Developmental Return",
              notes: "Ask the author to sharpen the argument and clarify what they are asserting. Explain what distinguishes an opinion piece from a reflective essay or case study. Suggest the appropriate genre if applicable."
            }
          ]
        },

        reflectiveEssay: {
          // [VERBATIM]
          threshold: "Is this submission genuinely analytical and reflective, or is it primarily a narrative account of a project?",
          note: "Reflective essays use the dialogic review process, which provides developmental feedback from reviewers. Apply a somewhat lighter touch at the desk stage: if there is genuine reflection and analytical intent, the dialogic process can carry the development. The floor, however, is this: a submission with no first-person analytical voice and no reflection on partnership as a lived experience should not proceed to the dialogic process regardless of its other qualities. The lighter touch applies to degree of development, not to the basic requirement that the submission is genuinely reflective.",
          findings: [
            {
              finding: "First-person, reflective, analytical. Illuminates the lived experience of partnership",
              outcome: "Proceed to Dialogic Review",
              notes: "Note any points to share with dialogic reviewers."
            },
            {
              finding: "Primarily narrative or descriptive, with no first-person analytical voice, or reads as a project report",
              outcome: "Revise Before Review or Developmental Return",
              notes: "Explain the distinction between narration and reflection. If the narrative is too dominant, ask for revision before the dialogic process. Suggest the case study genre if appropriate, in which case a new submission may be required."
            }
          ]
        },

        review: {
          // [VERBATIM]
          threshold: "Does this submission critically engage with the implications for students-as-partners practice, rather than merely summarizing the work reviewed?",
          note: null,
          findings: [
            {
              finding: "Critical engagement with partnership implications. Goes beyond summary",
              outcome: "Proceed to Review",
              notes: "Note any points for reviewer guidance or later feedback to author before sending out. Note reviews are normally reviewed within the EB."
            },
            {
              finding: "Mostly or purely summary, with limited or no critical engagement with partnership implications",
              outcome: "Revise Before Review or Developmental Return",
              notes: "Ask the author to develop the critical and partnership-relevant dimensions of the review. Explain what the journal expects from a review."
            }
          ]
        }
      }
    },

    // rubric.genreReferenceTable [VERBATIM] — collapsible reference panel, all stages
    genreReferenceTable: [
      {
        genre: "Research Article",
        wordLimit: "4,000-6,000 words",
        threshold: "Is there a clear methodology and a demonstrable contribution to knowledge?",
        commonGap: "Methodology and/or contribution absent, implicit, or underdeveloped: e.g. the paper reports findings without situating them in the field or explaining what they add."
      },
      {
        genre: "Case Study",
        wordLimit: "Up to 3,000 words",
        threshold: "Does the submission analyse rather than just describe, with strengths, weaknesses, impacts, and transferability addressed?",
        commonGap: "Overly descriptive: the submission narrates what happened with insufficient analysis as to why it matters or what worked and what did not."
      },
      {
        genre: "Opinion Piece",
        wordLimit: "Up to 900 words",
        threshold: "Is a clear position staked and supported by argument or evidence?",
        commonGap: "No discernible position: the piece reads as a reflection or overview rather than an argument."
      },
      {
        genre: "Reflective Essay",
        wordLimit: "Up to 3,000 words",
        threshold: "Is there genuine first-person analytical reflection, rather than narrative description of a project?",
        commonGap: "Narration without reflection: the submission describes events chronologically but does not analyse the lived experience of partnership."
      },
      {
        genre: "Review",
        wordLimit: "Up to 800 words",
        threshold: "Does the review critically engage with implications for partnership rather than summarizing?",
        commonGap: "Summary-only: the review describes the work reviewed without offering critical evaluation or partnership implications."
      }
    ],

    // rubric.tone [VERBATIM, final source sentence dropped as noted in the content document]
    // Stage 4, collapsible panel beside or above the email
    tone: "Desk rejection at IJSAP is not a closed door. The journal's developmental ethos applies at this stage as much as any other. Letters returning submissions should:\n\n- identify the specific issue clearly, without vagueness\n- explain what would be needed for the submission to proceed\n- invite revision and resubmission where the work has potential\n- suggest alternative genres or venues when appropriate\n\nThe tone of an Administrative Return letter is practical and instructional. The tone of a Developmental Return letter is constructive and specific. The tone of a Not Suitable for IJSAP letter is direct but generous: it explains why the work belongs elsewhere and points the author toward a more appropriate home."
  },

  emails: {

    // email.notSuitable [NEW] — Question 1A No, or "No genre fits" at Question 1B
    notSuitable: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nWe have completed an initial review of your submission and have determined that it is not suitable for IJSaP. [ADD: explain specifically how the submission is not about students-as-partners practice or process. For example: \"While your work involves student participants, the focus of the analysis is on [topic] rather than on the process or experience of working in partnership.\"]\n\nWe would encourage you to consider submitting this work to [ADD: suggest one or more alternative venues, such as a general higher education journal or a discipline-specific education journal].\n\nIf you would like to rework this submission, or develop a new one, to focus on students-as-partners practice or process, we would welcome a proposal. Please use the journal's proposal template, available at {{proposalTemplateURL}}.\n\nWe wish you well with your work.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.adminReturn [NEW] — one or more Layer 2 failures (excluding prior publication,
    // and excluding formatting when it is the sole failure). {{>failedChecks}} renders as
    // a bulleted list, one bullet per failed check, from fragments.check.*
    adminReturn: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nBefore we can assess your submission, the following needs to be addressed:\n\n{{>failedChecks}}\n\n[ADD: add any further detail the authors need, or delete this line.]\n\n{{>deadline}}\n\nPlease do not hesitate to contact us if you have any questions.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.genreRedirect [NEW] — Question 1B No with a suggested genre.
    // {{>genreCriteria}} inserts fragments.genreCriteria[suggested genre key].
    // {{>reflectiveEssayCaveat}} inserted only when the claimed or suggested genre is
    // Reflective Essay, silently omitted otherwise.
    genreRedirect: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nWe have completed an initial review of your submission. The work falls within the journal's scope, but we do not think it fits the {{genre}} category under which it was submitted. [ADD: explain briefly why the submission does not fit the claimed genre. For example: \"The submission narrates and reflects on your own experience of the partnership rather than presenting the structured analysis expected of a case study.\"]\n\nWe think the work would be a stronger fit as a {{suggestedGenre}}. {{>genreCriteria}}\n\nIf you would like to take this route, please prepare a new submission that meets the criteria for the {{suggestedGenre}} category. Because the criteria differ between categories, we ask for a new submission rather than a revision under the original article number. {{>reflectiveEssayCaveat}}\n\nWe hope you will consider this option, and we would be glad to see the work again in its new form. Please contact us if you have any questions.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.priorPublication [NEW] — prior publication check fails at Layer 2.
    // Outcome recorded as Not Suitable for IJSaP. No deadline.
    priorPublication: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nOur initial review indicates that this work [ADD: state what applies, for example \"has been previously published in [venue]\" or \"is currently under review at another journal\"]. IJSaP does not consider submissions that have been published elsewhere or that are under concurrent review, so we are unable to take this submission further.\n\nFor clarity, a manuscript previously presented as a conference paper or circulated as a working paper is acceptable under our policy. If you believe your submission falls into one of these categories, or that we have misunderstood its publication status, please contact us and we will be glad to look again.\n\nWe wish you well with your work.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.developmentalReturn [NEW] — Layer 3 outcome Developmental Return
    developmentalReturn: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nWe have completed an initial assessment of your submission. We can see the potential in this work, and we would like to encourage you to develop it further before we send it for peer review.\n\n[ADD: provide specific developmental guidance. Be clear and constructive. For example: \"At present, the submission reads primarily as a description of the partnership initiative rather than an analysis of it. We would encourage you to engage more directly with what the partnership experience meant for the participants, and to situate your analysis in relation to the existing literature on students as partners.\" Include as much specific guidance as is useful. The goal is to give the authors a clear path forward.]\n\n{{>deadline}} Please note that peer review will follow resubmission and may raise further points.\n\nWe look forward to seeing a revised version of your work.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.reviseBeforeReview [NEW] — Layer 3 outcome Revise Before Review
    reviseBeforeReview: {
      subject: "Your submission to IJSaP: {{submissionID}}",
      body: "Dear [ADD: author name(s)],\n\nThank you for submitting \"{{title}}\" to the International Journal for Students as Partners (IJSaP).\n\nWe have completed an initial assessment of your submission. Your work shows real promise and we would like to send it for peer review. Before we do, we are requesting some targeted revisions.\n\n[ADD: list specific, bounded revision requests. These should be more targeted than a developmental return, since the submission is close to ready. For example: \"Please clarify the contribution of the paper in relation to the existing literature. A paragraph in the introduction and a more developed discussion section would address this.\"]\n\n{{>deadline}}\n\nWe look forward to seeing the revised submission.\n\n{{editorNames}}\nOn behalf of the IJSaP Editorial Team"
    },

    // email.reviewerNotes [NEW] — Layer 3 outcome Proceed to Review (including dialogic).
    // Internal text, not an author email. No subject. Copy button reads "Copy reviewer notes".
    reviewerNotes: {
      subject: null,
      body: "REVIEWER GUIDANCE NOTES\n\nSubmission: {{submissionID}}, \"{{title}}\"\nGenre: {{genre}}\nAssessment date: {{date}}\nEditors: {{editorNames}}\n\nPoints to draw to reviewers' attention:\n[ADD: note any specific points for reviewers, for example methodological choices the authors should be asked to address, or areas where reviewer comment would be particularly welcome]\n\nNotes for the feedback letter after reviews come in:\n[ADD: note anything you would recommend adding to the feedback letter once reviews are received, so you do not need to reread the article at that stage]"
    }
  },

  fragments: {

    // fragments.check.* [NEW] — each renders as one bullet in the Administrative Return
    // email. Prior publication has no fragment: it routes to emails.priorPublication.
    check: {
      wordCount: "Word count: your submission is [ADD: actual word count] words. The limit for the {{genre}} category is {{wordLimitText}} words, excluding the abstract, author biographies, and the reference list. Please reduce the manuscript to within the limit before resubmitting.",
      fileFormat: "File format: please resubmit the manuscript as a Word document (.doc or .docx).",
      anonymization: "Anonymization: please remove all identifying information from the manuscript and any supplementary files, including author names, institutional names, and identifying references in the text, and check the file properties for author metadata.",
      ethicsStatement: "Ethics statement: the submission reports on research involving human participants but does not include an ethics statement. Please add a statement confirming that ethics approval was obtained, or explaining why approval was not required.",
      // Included only when other checks have also failed, per the rubric.
      formatting: "Formatting: please format the manuscript in 12-point Calibri, single spaced, with 1-inch margins."
    },

    // fragments.genreCriteria.* [NEW] — inserted into the Genre Redirect email for the
    // suggested genre
    genreCriteria: {
      researchArticle: "Research articles are 4,000 to 6,000 words (excluding abstract, biographies, and references) and present a clear methodology and a demonstrable contribution to knowledge in the field.",
      caseStudy: "Case studies are up to 3,000 words (excluding abstract, biographies, and references) and go beyond description to offer genuine analysis, including strengths, weaknesses, impacts, and transferability.",
      opinionPiece: "Opinion pieces are up to 900 words (excluding abstract, biographies, and references) and stake a clear position supported by argument, evidence, or lived experience.",
      reflectiveEssay: "Reflective essays are up to 3,000 words (excluding abstract, biographies, and references) and offer genuine first-person analytical reflection on the lived experience of partnership. Reflective essays are reviewed through an open dialogic process and are not anonymized.",
      review: "Reviews of books, conferences, or resources are up to 800 words (excluding abstract, biographies, and references) and critically engage with the implications of the work reviewed for students-as-partners practice."
    },

    // fragments.reflectiveEssayCaveat [NEW] — Genre Redirect email only, when the claimed
    // or suggested genre is Reflective Essay
    reflectiveEssayCaveat: "Please note that reflective essays use an open dialogic review process and are not anonymized, while submissions in other categories undergo anonymized review, so the manuscript will need to be anonymized or deanonymized accordingly.",

    // fragments.deadline [NEW] — Administrative Return, Developmental Return, and Revise
    // Before Review emails. {{deadline}} computed per meta.deadlines from today's date.
    deadline: "Please make the necessary changes and resubmit using your original article number ({{submissionID}}) by {{deadline}}. If we do not receive your amended submission by that date, we will remove it from the system and you will need to begin a new submission.",

    // fragments.recordSummary [NEW] — "Copy record summary" button on Stage 4, for pasting
    // into OJS as an editorial note. Omit the "Reviewed by" line when the field is empty.
    recordSummary: "DESK REVIEW RECORD\nSubmission: {{submissionID}}, \"{{title}}\"\nGenre: {{genre}}\nOutcome: {{outcome}} (decided at {{layer}})\nKey reason: {{keyReason}}\nEditors: {{editorNames}}\nAssessment date: {{date}}\nReviewed by: {{reviewedBy}}\nRecord link: {{shareableURL}}"
  },

  ui: {
    tokenPrompt: "This tool is for IJSaP editorial teams. Enter the access token to continue. If you do not have the token, contact the Editorial Manager.",
    tokenError: "That token was not recognized. Check it and try again.",
    formattingBanner: "Formatting issues noted. They have been recorded in the assessment and will be raised at the feedback stage after review, since formatting alone does not trigger a return.",
    reviewNotice: "You are reviewing a saved assessment. Edit any fields as needed, then click Save updates. Use Save as new record if you want to keep the original assessment unchanged.",
    genreChangedNotice: "The genre has changed, so the Layer 3 threshold assessment has been reset. Layers 1 and 2 are unchanged. Please redo Layer 3 using the criteria for the new genre.",
    addWarning: "The text still contains [ADD] prompts. Complete or remove them before sending.",
    saveError: "The record could not be saved. Your work has not been lost. Check your connection and try again.",
    recordNotFound: "No record was found for this link. The record may have been removed, or the link may be incomplete. Check the URL and try again.",
    networkError: "The record could not be loaded because the server could not be reached. This looks like a connection problem rather than a missing record. Check your connection and try again.",
    conflictWarning: "This record has been changed since you loaded it, most likely by your co-editor. To avoid overwriting their work, reload the record to see the latest version, or use Save as new record to keep your version as a separate record.",
    restorePrompt: "You have an unfinished assessment from a previous session. You can restore it and continue where you left off, or start fresh."
  }
};
